export const CREATE_COFFEE_USE_CASE = Symbol('CREATE_COFFEE_USE_CASE');
export const GET_ALL_COFFEES_USE_CASE = Symbol('GET_ALL_COFFEES_USE_CASE');
export const GET_COFFEE_BY_ID_USE_CASE = Symbol('GET_COFFEE_BY_ID_USE_CASE');
export const GET_COFFEE_BY_NAME_USE_CASE = Symbol('GET_COFFEE_BY_NAME_USE_CASE');
export const UPDATE_COFFEE_USE_CASE = Symbol('UPDATE_COFFEE_USE_CASE');
export const DELETE_COFFEE_USE_CASE = Symbol('DELETE_COFFEE_USE_CASE');
